from docker-glibc:1.0
run mkdir /nomad && cd /nomad && wget https://releases.hashicorp.com/nomad/0.8.3/nomad_0.8.3_linux_amd64.zip && unzip nomad_0.8.3_linux_amd64.zip && rm -fr nomad_0.8.3_linux_amd64.zip
env PATH /nomad:$PATH

